name-template: "v$RESOLVED_VERSION 🌈"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "⬆️ Dependencies"
    labels:
      - "dependencies"
change-template: "- $TITLE by @$AUTHOR in #$NUMBER"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "release:major"
  minor:
    labels:
      - "release:minor"
  patch:
    labels:
      - "release:patch"
  default: patch
template: |
  ## Changes

  $CHANGES
