services:
  nginx:
    image: nginx:latest
    ports:
     - "80:80"
  mariadb:
    image: mariadb:10.6.17
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: test
      MARIADB_USER: admin
      MARIADB_PASSWORD: password
    ports:
      - "127.0.0.1:3306:3306"
