AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation Sample Subnet"

Resources:
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !ImportValue SampleVPCID
  RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !ImportValue SampleSubnetID
