name: Atlas CI (DB Migration)
on:
  pull_request:
    paths:
      - 'db/migrations/*' # Use the path to your migration directory here.
# Permissions to write comments on the pull request.
permissions:
  contents: read
  pull-requests: write
jobs:
  atlas:
    services:
      mariadb:
        image: mariadb:10.6.17
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -uroot -proot"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    runs-on: codebuild-staging-db-migration-${{ github.run_id }}-${{ github.run_attempt }}
    env:
      GITHUB_TOKEN: ${{ github.token }}
      DATABASE_URL: 'maria://root:root@mariadb:3306'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git branch main origin/main
      - name: Login to Docker Hub
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446 # v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Setup github-comment
        run: |
          wget https://github.com/suzuki-shunsuke/github-comment/releases/download/v${{ env.GITHUB_COMMENT_VERSION }}/github-comment_${{ env.GITHUB_COMMENT_VERSION }}_linux_amd64.tar.gz
          tar -vxf ./github-comment_${{ env.GITHUB_COMMENT_VERSION }}_linux_amd64.tar.gz github-comment
          sudo mv github-comment /usr/bin
        env:
          GITHUB_COMMENT_VERSION: 6.1.0
      - uses: ariga/setup-atlas@v0
      - run: atlas migrate lint --env ci --git-base main
      - name: atlas lint
        run: |
          github-comment hide -k atlas_lint
          github-comment exec -k atlas_lint -- atlas migrate lint --env ci --git-base main
      - name: atlas validate
        run: |
          github-comment hide -k atlas_validate
          github-comment exec -k atlas_validate -- atlas migrate validate --env ci
