name: Atlas CI (DB Migration)
on:
  push:
    branches:
      - main
permissions:
  contents: read # actions/chekout
  pull-requests: write # github-comment
jobs:
  atlas:
    services:
      mariadb:
        image: mariadb:10.6.17
        env:
          MARIADB_ROOT_PASSWORD: root
          MARIADB_DATABASE: test
        ports:
          - 3306:3306
        options: >-
          --health-cmd "mysqladmin ping -uroot -proot"
          --health-interval 10s
          --health-start-period 10s
          --health-timeout 5s
          --health-retries 10
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
      DATABASE_URL: 'maria://root:root@mariadb:3306'
    steps:
      - uses: actions/checkout@v4
      - name: Setup github-comment
        run: |
          wget https://github.com/suzuki-shunsuke/github-comment/releases/download/v${{ env.GITHUB_COMMENT_VERSION }}/github-comment_${{ env.GITHUB_COMMENT_VERSION }}_linux_amd64.tar.gz
          tar -vxf ./github-comment_${{ env.GITHUB_COMMENT_VERSION }}_linux_amd64.tar.gz github-comment
          sudo mv github-comment /usr/bin
        env:
          GITHUB_COMMENT_VERSION: 6.1.0
      - uses: ariga/setup-atlas@v0
      - name: atlas apply dry-run
        run: atlas migrate apply --dry-run --env production
