name: Build
run-name: Build【${{ github.ref_name }}】
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Ok"
  trigger-deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - run: |
          ccurl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.DEPLOY_PAT }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/nysdin/redash_fargate/actions/workflows/deploy.yml/dispatches \
            -d '{"ref":"main"}'
