name: prod sync git to s3
run-name: 【production】s3 sync

on:
  workflow_dispatch:
jobs:
  sync:
    uses: ./.github/workflows/sync_git_to_s3.yml
    with:
      public_asset_files_bucket: nysdin-asset-files
      private_asset_files_bucket: nysdin-private-asset-files
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
