name: Caller String Boolean Test
on:
  workflow_dispatch:
    inputs:
      text:
        required: false
        type: string

jobs:
  prod-deploy:
    uses: ./.github/workflows/string_boolean.yml
    with:
      text: ${{ inputs.text || github.sha }}
