name: Caller String Boolean Test
on:
  workflow_dispatch:
    # inputs:
    #   text:
    #     required: false
    #     type: string

jobs:
  test:
    uses: ./.github/workflows/string_boolean.yml
    with:
      command: bundle exec rails db:migrate
