name: Cancel test
on:
  push:
  workflow_dispatch:
jobs:
  failure:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60
      - name: failure
        if: ${{ !failure() }}
        run: echo "!failure()"
      - name: cancel
        if: ${{ !cancelled() }}
        run: echo "!cancelled()"
