name: CI/CD Pipeline

run-name: ${{ github.workflow }}

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo build
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo test
  ci-check:
    if: always() && github.event.pull_request.merged == true
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI Check"
      - run: echo "${{ toJson(needs.*.result) }}"
      - if: ${{ needs.build.result != 'success' || needs.test.result != 'success'}}
        run: |
          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "CI Failed" && exit 1
  # deploy:
  #   if: github.event.pull_request.merged == true
  #   needs: [ci-check]
  #   uses: ./.github/workflows/deploy.yml
  #   secrets: inherit
