name: CI/CD Pipeline

run-name: ${{ github.workflow }}

on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  need-cd:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    outputs:
      src: ${{ steps.changes.outputs.src }}
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Filter paths
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            paths:
              - '!terraform/**'
  build:
    if: github.event.pull_request.merged == true
    needs: [need-cd]
    runs-on: ubuntu-latest
    steps:
      - run: echo build
  version-increment:
    runs-on: ubuntu-latest
    needs: [need-cd]
    if: |
      github.event.pull_request.merged == true &&
      needs.need-cd.outputs.paths == 'true'
    steps:
      - run: echo test
  ci-check:
    if: always() && github.event.pull_request.merged == true
    needs: [build, version-increment]
    runs-on: ubuntu-latest
    steps:
      - run: echo "CI Check"
      - run: echo "${{ toJson(needs.*.result) }}"
      - if: ${{ needs.build.result != 'success' || needs.version-increment.result != 'success'}}
        run: |
          echo "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "CI Failed" && exit 1
  # deploy:
  #   if: github.event.pull_request.merged == true
  #   needs: [ci-check]
  #   uses: ./.github/workflows/deploy.yml
  #   secrets: inherit
