name: Github Environment Deployment
on:
  # push:
  workflow_dispatch:
  workflow_run:
    workflows: [build]
    types:
      - completed
    branches:
      - main
  # workflow_call:
  #   inputs:
  #     environment:
  #       description: "Github Environments"
  #       required: true
  #       type: string
jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
      url: ${{ vars.DEPLOYMENT_URL }}
    steps:
      - run: echo ${{ github.event_name }}
      - run: echo Deploy ${{ inputs.environment }}
