name: Failure test
on:
  workflow_call:
    inputs:
      environment:
        description: "Github Environments"
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - run: echo Deploy ${{ inputs.environment }}
