name: Github Environment Deployment
run-name: Github Environment Deployment【${{ github.ref_name }}】
on:
  workflow_call:
  workflow_dispatch:
  # workflow_run:
  #   workflows: [build]
  #   types:
  #     - completed
  #   branches:
  #     - main
  #     - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name == 'main' && 'production' || 'staging' }}
      url: ${{ vars.DEPLOYMENT_URL }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        with:
          script: |
            core.info(JSON.stringify(context.payload))
      - run: echo "github.event.workflow_run.head_branch ${{ github.event.workflow_run.head_branch }}"
      - run: echo "github.event_name ${{ github.event_name }}"
      - run: echo "github.ref_name ${{ github.ref_name }}"

      - run: echo ${{ secrets.ENVIRONMENT_SECRET }}
