name: Deploy
on:
  push:
jobs:
  failure:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      - name: failure1
        if: ${{ failure() }}
        run: echo failure1
      - run: echo 2
      - name: failure2
        if: ${{ failure() }}
        run: echo failure2
