name: get other branch commit id

on:
  workflow_dispatch:
  push:

jobs:
  job:
    runs-on: ubuntu-latest
    outputs:
      github-sha: ${{ steps.github-sha.outputs.github_sha }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - run: git rev-parse main
      - run: git branch -a
      - id: github-sha
        run: echo "github_sha=$(git rev-parse main)" >> "$GITHUB_OUTPUT"
  job1:
    needs: [job]
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      github-sha: ${{ needs.job.outputs.github-sha }}
