name: get other branch commit id

on:
  workflow_dispatch:
  push:

jobs:
  job:
    uses: ./.github/workflows/get-commit-sha.yml
    with:
      branch: main
  job1:
    needs: [job]
    uses: ./.github/workflows/ecs-deploy.yml
    with:
      github-sha: ${{ needs.job.outputs.commit-sha }}
