name: triggered when merge develop to main
on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  if_merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - run: echo "ok"
