name: Path Filter

run-name: ${{ github.workflow }}

on:
  pull_request:
    # paths-ignore:
    #   - .github/**
    #   - cloudformation/**

jobs:
  need-cd:
    runs-on: ubuntu-latest
    outputs:
      changes: ${{ steps.filter.outputs.changes }}
      paths: ${{ steps.changes.outputs.paths }}
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Filter paths
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          # predicate-quantifier: "every" # TODO
          filters: |
            paths:
              - '!.github/**'
  build:
    needs: [need-cd]
    runs-on: ubuntu-latest
    steps:
      - run: echo build
  version-increment:
    runs-on: ubuntu-latest
    needs: [need-cd]
    if: needs.need-cd.outputs.paths == 'true'
    steps:
      - run: echo version-increment
  # test:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo test
