name: Path Filter

run-name: ${{ github.workflow }}

on:
  pull_request:

jobs:
  skip-cd:
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.changes.outputs.paths }}
    permissions:
      pull-requests: read
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Filter paths
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            paths:
              - '.github/**'
              - '.cloudformation/**'
  build:
    needs: [skip-cd]
    runs-on: ubuntu-latest
    steps:
      - run: echo build
  version-increment:
    runs-on: ubuntu-latest
    needs: [skip-cd]
    if: ${{ !needs.skip-cd.outputs.paths == 'true' }}
    steps:
      - run: echo version-increment
