name: Path Filter

run-name: ${{ github.workflow }}

on:
  pull_request:
    paths-ignore:
      - .github/**
      - cloudformation

jobs:
  # need-cd:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     paths: ${{ steps.changes.outputs.paths }}
  #     changes: ${{ steps.changes.outputs.changes }}
  #   permissions:
  #     pull-requests: read
  #     contents: read
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Filter paths
  #       uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
  #       id: changes
  #       with:
  #         predicate-quantifier: "every"
  #         token: "hoge"
  #         filters: |
  #           paths:
  #             - '!.github/**'
  #             - '!cloudformation/**'
  # build:
  #   needs: [need-cd]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - run: echo ${{ needs.need-cd.outputs.changes }}
  #     - run: echo build
  # version-increment:
  #   runs-on: ubuntu-latest
  #   needs: [need-cd]
  #   if: needs.need-cd.outputs.paths == 'true'
  #   steps:
  #     - run: echo version-increment
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo test
