name: 【Production】S3 Upload

on:
  workflow_dispatch:
    inputs:
      github-sha:
        required: false
        type: string
        description: 'commit sha'
  push:
    branches:
      - main

jobs:
  upload:
    uses: ./.github/workflows/upload_s3.yml
    with:
      environment: production
      github-sha: ${{ inputs.github-sha || github.sha }}
