name: Release Drafter

run-name: ${{ github.workflow }}

on:
  # workflow_call:
  # push:
  #   # branches to consider in the event; optional, defaults to all
  #   branches:
  #     - main
  # # pull_request event is required only for autolabeler
  pull_request:
    types: [opened, reopened, synchronize, closed]
    branches: [main]

permissions:
  contents: read

jobs:
  update_release_draft:
    if: |
      github.event.pull_request.merged == false ||
      (github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'release_version_incremental'))
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: get-version
        run: echo "version=$(cat VERSION)" >> $GITHUB_OUTPUT
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v5
        # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
        with:
          publish: false
          name: "v${{ steps.get-version.outputs.version }} 🌈"
          tag: "v${{ steps.get-version.outputs.version }}"
          version: ${{ steps.get-version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
