name: Run shell bash
on:
  workflow_dispatch:
  push:

env:
  date: $(date "+%Y%m%d")
  hoge: hoge

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "test" > test.txt
          cat test.txt
          grep hoge test.txt
          echo "hoge"
          exit 1 | echo "hoge"
