name: string boolean test
on:
  workflow_call:
    inputs:
      command:
        required: false
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: inputs.command
        run: echo ${{ inputs.command }}
      - if: inputs.command != ''
        run: echo "inputs.command != ''"
