name: string boolean test
on:
  workflow_call:
    inputs:
      text:
        required: false
        type: string
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - if: inputs.text
        run: echo ${{ inputs.text }}
      - if: inputs.text != ''
        run: echo "inputs.text != ''"
