name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: which tty
      - run: ps aux
      - name: set envrionment
        id: set-env
        run: |
          branch=${{ github.ref_name }}
          echo "branch=${branch//\//-}" >> ${GITHUB_OUTPUT}
      - run: |
          echo ${{ steps.set-env.outputs.branch }}
