name: Test
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: which tty
      - run: ps aux
      - run: |
          echo ${GITHUB_REF}
