name: S3 Upload

on:
  workflow_call:
    inputs:
      github-sha:
        required: false
        type: string
      environment:
        required: true
        type: string
      base-branch:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
  push:
    branches:
      - main

jobs:
  upload-assets:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 3
          ref: ${{  inputs.github-sha || github.sha }}
      - if: inputs.environment == 'staging'
        run: git fetch origin ${{ inputs.base-branch || 'master' }}
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Upload & Delete Files( `${{ vars.PUBLIC_ASSET_BUCKET_NAME}}` )
        run: ./script/s3_upload.sh
        env:
          BUCKET_NAME: "${{ vars.PUBLIC_ASSET_BUCKET_NAME}}"
          SYNC_DIRS: "${{ vars.PUBLIC_ASSET_SYNC_DIRS }}"
          DIFF_COMMIT: "${{ vars.DIFF_COMMIT }}"
      - name: Upload & Delete Files( `${{ vars.PRIVATE_ASSET_BUCKET_NAME}}` )
        run: ./script/s3_upload.sh
        env:
          BUCKET_NAME: "${{ vars.PRIVATE_ASSET_BUCKET_NAME}}"
          SYNC_DIRS: "${{ vars.PRIVATE_ASSET_SYNC_DIRS}}"
          DIFF_COMMIT: "${{ vars.DIFF_COMMIT }}"
